export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCSESS = 'CREATE_ORDER_SUCCSESS'
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE'



export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST'
export const GET_ORDER_BY_ID_SUCCSESS = 'GET_ORDER_BY_ID_SUCCSESS'
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE'


export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST'
export const GET_ORDER_HISTORY_SUCCSESS = 'GET_ORDER_HISTORY_SUCCSESS'
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE'